name: Upload Files to Server

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Delete Files with curl
      run: |
        curl -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }}" -X DELETE https://your-server-url/www/

    - name: Upload Files with curl
      run: |
        for file in $(find . -type f); do
          curl -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }}" -T "$file" https://your-server-url/www/
        done
