name: Upload Files to Server

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install requirments
      run: |
        sudo apt-get install ftp
        done

