name: sync repo to server

on:
  push:
    branches:
      - main

jobs:
  ftp-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install lftp
      run: sudo apt-get install lftp

    - name: Delete all files inside www on FTP server and sync repo
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -f "
        open ftp://$FTP_SERVER
        user $FTP_USERNAME $FTP_PASSWORD
        mirror -R --delete --exclude .git/ --exclude .github/ ./ /www
        quit
        "

