name: Upload Files to Server

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Delete Files Inside /www/ Folder
      run: |
        curl -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }}" -X PROPFIND --depth 1 https://${{ secrets.WEBDAV_HOST }}/www/ | grep '<D:href>' | sed -e 's/<D:href>//g' -e 's/<\/D:href>//g' | while read -r file; do
          if [[ "$file" != "www/" ]]; then
            curl -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }}" -X DELETE "$file"
          fi
        done

    - name: Upload Files with curl
      run: |
        for file in $(find . -type f); do
          curl -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }}" -T "$file" https://${{ secrets.WEBDAV_HOST }}/www/
        done

