name: Upload Files to Server

on:
  push:
    branches:
      - main 

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Delete Files on Server via WebDAV
      run: |
        sudo apt-get update
        sudo apt-get install -y cadaver
        echo "$WEBDAV_PASSWORD" > /tmp/webdav_password
        cadaver <<EOF
        open https://${{ secrets.WEBDAV_HOST }}${{ secrets.WEBDAV_PATH }}/www
        username ${{ secrets.WEBDAV_USER }}
        mdelete *
        EOF
      env:
        WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}

    - name: Upload Files to Server via WebDAV
      run: |
        sudo apt-get update
        sudo apt-get install -y cadaver
        echo "$WEBDAV_PASSWORD" > /tmp/webdav_password
        cadaver <<EOF
        open https://${{ secrets.WEBDAV_HOST }}${{ secrets.WEBDAV_PATH }}/www
        username ${{ secrets.WEBDAV_USER }}
        lcd .
        put -r ./*
        EOF
      env:
        WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
